# Generated by Django 4.1.3 on 2022-11-03 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(blank=True, default='static/dist/img/anonimo.png', upload_to='JogoDoBicho/src/img/pessoas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('grupo', models.IntegerField(verbose_name='Grupo')),
                ('icone', models.ImageField(blank=True, upload_to='JogoDoBicho/src/img/animais')),
                ('dezenhas', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(blank=True, default='static/dist/img/anonimo.png', upload_to='JogoDoBicho/src/img/pessoas')),
                ('saldo', models.FloatField(default=0.0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='static/dist/img/banner.jpg', upload_to='JogoDoBicho/src/img/banners')),
                ('registro', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=14)),
                ('fim', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JogoDoBicho.categoria', verbose_name='Categoria')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JogoDoBicho.administrador', verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LanceLT',
            fields=[
                ('lance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JogoDoBicho.lance')),
            ],
            bases=('JogoDoBicho.lance',),
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now=True)),
                ('posicao', models.IntegerField(verbose_name='Posição')),
                ('resultado', models.CharField(max_length=11)),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('ganhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JogoDoBicho.cliente', verbose_name='Ganhador')),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JogoDoBicho.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LanceJB',
            fields=[
                ('lance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JogoDoBicho.lance')),
                ('premios', models.ManyToManyField(related_name='Premios', to='JogoDoBicho.premio')),
            ],
            bases=('JogoDoBicho.lance',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fim', models.DateTimeField()),
                ('lance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='JogoDoBicho.lancejb', verbose_name='Lance')),
            ],
        ),
        migrations.CreateModel(
            name='ApostaLT',
            fields=[
                ('aposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JogoDoBicho.aposta')),
                ('lance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JogoDoBicho.lancejb', verbose_name='Lance')),
            ],
            bases=('JogoDoBicho.aposta',),
        ),
        migrations.CreateModel(
            name='ApostaJB',
            fields=[
                ('aposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JogoDoBicho.aposta')),
                ('escolhas', models.ManyToManyField(related_name='Escolhas', to='JogoDoBicho.bicho')),
                ('lance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JogoDoBicho.lancejb', verbose_name='Lance')),
            ],
            bases=('JogoDoBicho.aposta',),
        ),
    ]
