# Generated by Django 4.1.3 on 2022-11-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bank_account',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
