# Generated by Django 4.1.3 on 2022-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSena', '0002_remove_profile_user_delete_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='concourse',
        ),
        migrations.AddField(
            model_name='bet',
            name='concourse',
            field=models.ManyToManyField(to='MegaSena.concourse'),
        ),
    ]
