# Generated by Django 4.1.3 on 2022-11-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSena', '0003_remove_bet_concourse_bet_concourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='surpresinha',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='value',
            field=models.FloatField(blank=True, default=4.5, null=True),
        ),
    ]
