# Generated by Django 4.1.3 on 2022-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSena', '0006_alter_bet_results_alter_bet_surpresinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='numbers',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bet',
            name='surpresinha',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
